name: 🚀🚀🚀🚀🚀🚀🚀🚀🚀 Deploy
on:
  push:
    branches:
      - master
      - dev
  pull_request: { }

permissions:
  actions: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge-reports:
    permissions:
      pull-requests: write
      checks: write
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - name: Install dependencies
#        run: npm ci
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#      - name: Run Playwright tests
#        run: npx playwright test @smoke

      - name: Hello PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const username = context.payload.pull_request.user.login;
            const message = `Hello @${username}! 👋 Welcome to the PR. Your PR number is ${prNumber}`.
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
